#!/bin/sh
# conkyrestart
# kills conky and restarts it.

if [ "$(pidof conky)" ]; then
    killall conky && conky -c ~/.config/conky.conf &
    exit
else
    conky -c ~/.config/conky.conf &
    exit
fi
